INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('11', 'readingRoomHeaderBlock', 'Reading Room Header', 'reading-room-header-block', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('12', 'readingRoomBlockOne', 'Reading Room Block One', 'reading-room-block-1', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('13', 'readingRoomBlockTwo', 'Reading Room Block Two', 'reading-room-block-2', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('14', 'readingRoomBlockThree', 'Reading Room Block Three', 'reading-room-block-3', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('15', 'readingRoomBlockFour', 'Reading Room Block Four', 'reading-room-block-4', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('16', 'readingRoomBlockFive', 'Reading Room Block Five', 'reading-room-block-5', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('17', 'readingRoomBlockSix', 'Reading Room Block Six', 'reading-room-block-6', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('18', 'readingRoomBlockSeven', 'Reading Room Block Seven', 'reading-room-block-7', 'READINGROOM', '1');
INSERT INTO `vhmml`.`blocks` (`id`, `name`, `display_name`, `style_name`, `section`, `is_enabled`) VALUES ('19', 'readingRoomBlockEight', 'Reading Room Block Eight', 'reading-room-block-8', 'READINGROOM', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('11', 'reading-room-header-block-image-1', 'IMAGE', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-heading', 'HEADING', 'Reading Room', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-content', 'CONTENT', 'vHMML Reading Room provides access to thousands of items in HMML\'s collections', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('11', 'reading-room-header-block-url', 'URL', '/readingRoom', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('12', 'reading-room-block-1-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('12', 'reading-room-block-1-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('13', 'reading-room-block-2-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('13', 'reading-room-block-2-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('14', 'reading-room-block-3-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('14', 'reading-room-block-3-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('15', 'reading-room-block-4-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('15', 'reading-room-block-4-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('16', 'reading-room-block-5-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('16', 'reading-room-block-5-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('17', 'reading-room-block-6-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('17', 'reading-room-block-6-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('18', 'reading-room-block-7-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('18', 'reading-room-block-7-hover-color', 'HOVERCOLOR', '#000000', '1');

INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `is_enabled`) VALUES ('19', 'reading-room-block-8-image', 'IMAGE', '0');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-heading', 'HEADING', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-heading-color', 'HEADINGCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-content', 'CONTENT', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-content-color', 'CONTENTCOLOR', '#FFFFFF', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-overlay-color', 'OVERLAYCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-overlay-opacity', 'OVERLAYOPACITY', '0', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-background-color', 'BACKGROUNDCOLOR', '#000000', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-url', 'URL', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-field-link-search', 'FIELDLINKSEARCH', '', '1');
INSERT INTO `vhmml`.`block_components` (`block_id`, `style_name`, `type`, `value`, `is_enabled`) VALUES ('19', 'reading-room-block-8-hover-color', 'HOVERCOLOR', '#000000', '1');
