ALTER TABLE users
ADD COLUMN addressOne VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN addressTwo VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN country VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN state VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN city VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN zipCode VARCHAR(12) NULL DEFAULT NULL;